#goal definition
string goal
string target_name
geometry_msgs/Pose target_pose
float64 odom_move_ms
float64 odom_spin_rad
---
#result definition
string result
int64 returncode
---
#feedback
string feedback
geometry_msgs/Pose base_position
